agent:
  _target_: IRL.algorithms.manual.ManualAgent

saved_model_folder_extra: "default"
saved_model_timestamp: ""
saved_model_folder: ./models/manual/${environment.meta.name}/${algorithm.saved_model_folder_extra}/seed_${train.common.seed}${algorithm.saved_model_timestamp}/
saved_model_name: best_model.zip
saved_model_path: ${algorithm.saved_model_folder}${algorithm.saved_model_name}