config:
  _target_: IRL.environments.ant.Ant
  render_mode: null
  max_episode_steps: 1000    # Set to 1000 to match D4RL
  history_len: 2
  seed: ${train.common.seed}
  # use_contact_forces: True # to correspond to d4rl's dataset format 

meta:
  name: Ant

d4rl:
  env_name: ant
  min_score: -325.6
  max_score: 3879.7
  dataset_type: expert    # options [random, medium, medium_expert, expert]
  dataset_random_url: https://rail.eecs.berkeley.edu/datasets/offline_rl/gym_mujoco/ant_random.hdf5
  dataset_medium_url: https://rail.eecs.berkeley.edu/datasets/offline_rl/gym_mujoco/ant_medium.hdf5
  dataset_expert_url: https://rail.eecs.berkeley.edu/datasets/offline_rl/gym_mujoco/ant_expert.hdf5
  dataset_medium_expert_url: https://rail.eecs.berkeley.edu/datasets/offline_rl/gym_mujoco/ant_medium_expert.hdf5
