config:
  _target_: IRL.environments.relocate.Relocate
  render_mode: null
  max_episode_steps: 200
  history_len: 2
  seed: ${train.common.seed}

meta:
  name: Relocate

d4rl:
  env_name: relocate
  min_score: -6.425911 
  max_score: 4233.877797728884
  dataset_type: expert-v1   # options [cloned-v1, human-v1, expert-v1]
  dataset_cloned-v1_url: https://rail.eecs.berkeley.edu/datasets/offline_rl/hand_dapg_v1/relocate-cloned-v1.hdf5
  dataset_human-v1_url: https://rail.eecs.berkeley.edu/datasets/offline_rl/hand_dapg_v1/relocate-human-v1.hdf5
  dataset_expert-v1_url: https://rail.eecs.berkeley.edu/datasets/offline_rl/hand_dapg_v1/relocate-expert-v1.hdf5