common:
  batch_size: 128
  train_steps: 1000000
  train_log_interval: 1000
  eval_frequency: 5000
  eval_episodes: 25
  seed: 0
  device: cuda:0
  data_fraction: 1.0

eval_callback:
  _target_: stable_baselines3.common.callbacks.EvalCallback
  best_model_save_path: ${algorithm.saved_model_folder}
  log_path: ${algorithm.saved_model_folder}
  eval_freq: ${train.common.eval_frequency}
  n_eval_episodes: ${train.common.eval_episodes}
  deterministic: True
  render: False
